### ISSUE TITLE
Add dedicated columns to name tables

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#404]
Some columns in the names table have two lines but now that we have more space we could add dedicated columns (except for block and time columns).

**Comment by danilosierrac** [comment]
I WANT THIS <3

**Comment by danilosierrac** [comment]
For block and time columns, I found this cool idea from Etherscan. You can basically let people choose what they want to see on click so you can use block, calendar, time elapse or time remaining. I would LOVE to use this because it really opens up the possibilities to keep data organized and makes aeScan useful even for accounting :) 

https://github.com/aeternity/aescan/assets/7396728/09a38850-fdb0-441a-9c15-37fe98051447
