### ISSUE TITLE
Research how to decode multiple contracts events

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#442]
Research what needs to be done to decode events of smart contracts in the frontend with a particular focus on cases when multiple events of different smart contracts should be decoded.

The current possible sections are:
- Contract events page
- Token events
- Account activities

**Comment by michele-franchi** [comment]
- Collect some ACIs for non-standard contracts
- Collect some events
- Check with SDK if it's possible to decode events, especially with tables with events coming from different smart contracts

Example contract:
https://github.com/aeternity/ga-multisig-contract/tree/4d6fd1355bbfb9e8dd09c96f23d7176e45e8a4ae/contracts

**Comment by lukeromanowicz** [comment]
It is possible to decode any contract transaction or event referring to the root transaction by transactionId and ACI.

Currently, it's not possible to decode event from the middleware without the the transaction because it doesn't provide the complete event data, which is address, data (in bytecode format), and topics. The contract address is known, but the data and full topics are missing. 

Example of required event data:


![Image](https://github.com/aeternity/aescan/assets/46789227/d1fb63c4-ff52-419b-a44e-27750f9e5526)


Example of event representation from the mdw:


![Image](https://github.com/aeternity/aescan/assets/46789227/2209688b-d8a3-4781-89bf-2ad86dc7ee2d)

I suppose it shouldn't be very tricky to add the original raw node event data to the partially decoded entity

**Comment by michele-franchi** [comment]
If the HTTP compiler is needed I see [an issue here](https://github.com/aeternity/aescan/compare/POC-decoding-events?expand=1#diff-8170e5cc6136da2eadfc3ca6ae1fa0c15bcd80e9291cc363232bf3112b11ac66R294), the plan is to shut it down.

**Comment by michele-franchi** [comment]
I did a quick test and it seems to be not necessary for the decoding.

**Comment by michele-franchi** [comment]
@lukeromanowicz could you open an issue on mdw?

**Comment by lukeromanowicz** [comment]
Created: https://github.com/aeternity/ae_mdw/issues/1532

Closing this task as discussed during the daily
