### ISSUE TITLE
Transactions stats

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#447]
Along with charts we could elaborate some ideas to display the following stats, in the [transactions page](https://aescan.io/transactions):
- Total transactions (with live increase)
- Last day transactions (with live increase)

to make the transactions page less static.

**Comment by danilosierrac** [comment]
Yeah, transactions can be ticking constantly like in this example:

https://github.com/aeternity/aescan/assets/7396728/44736377-9ad7-46dd-b19c-0f3c8af1b4b5

You can also view it live here: https://solana.com/

**Comment by danilosierrac** [comment]
Maybe we should blend both chart and stats tasks into one because I need to decide interdependently. Is that possible? Here is al ist of things I want to do based of preliminary assumptions about "things I would like to see graphically":

### List of things I want to know about aeternity

### About the blockchain and transactions

- How many names have been claimed
- Blocks mined
- How many people are developing on it
- How distributed/decentralized is it
- Total accounts
- Total transactions
- 	In real time
- 	Pending
- Total transfer volume
- Price fluctuation in perspective
- If a transaction went through, is pending or not
- When things happened with real dates as well as block dates

### About accounts

- When exactly their transactions incurred: Latest 25 from a total of 61 transactions (for taxes, reporting, for actual movement)
- Volume traded
- Names owned
- Balance
- Last account activity
- 	Last transaction sent
- 	First transaction sent

Now as a next step I have to re arrange them. Probably on the dashboard. On the æternity homepage we have this data:

Transactions
Blocks mined
Github commits (would love to change it to something else)
Names claimed

Adding screenshots of data ideas



![Image](https://github.com/aeternity/aescan/assets/7396728/c9349931-6482-422d-95be-5cdb809b6fbb)
![Image](https://github.com/aeternity/aescan/assets/7396728/85f83d8c-f2f8-4daf-b04a-2e7f8eb1d1e2)
![Image](https://github.com/aeternity/aescan/assets/7396728/c574b8bf-d535-4292-99c1-cd15c3fe9abb)
![Image](https://github.com/aeternity/aescan/assets/7396728/caa3c58b-f5bb-49d9-be70-78290516f5fa)

**Comment by janmichek** [comment]
@michele-franchi I forgot what was the resolution for AVG TRANSACTION FEE. Can you repeat please?

**Comment by janmichek** [comment]
> @michele-franchi I forgot what was the resolution for AVG TRANSACTION FEE. Can you repeat please?

Ping @michele-franchi
