### ISSUE TITLE
Name history

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#73]
The name history of a long name (13+ characters) that doesn’t need an auction could look as follows:

![image](https://github.com/aeternity/aescan/assets/11598532/0bb91c8e-02ab-480e-928e-c3592b53b7c8)

The name history of a short name (<13 characters) that needs an auction could look as follows:

<img width="1127" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/186bc618-af91-445d-80ff-e2354dea2a24">

Other name activities:

<img width="1117" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/69364881-ae5e-4108-be4b-e3ba35a1aeec">

Open questions:
* How to find out if NameClaimTx is: an “auction initializer”, “auction bid” or just “name activation” in case there is no auction?
* How to find out that the auction took place and has ended + easily define who won it?
* How to find out if the name is expired?

Tracking: https://github.com/aeternity/ae_mdw/issues/1202

Sample endpoint: https://mainnet.aeternity.io/mdw/v2/names/superhero.chain/history

**Comment by janmichek** [comment]
Still open on MDW side

**Comment by michele-franchi** [comment]
Not blocked anymore, ready to be checked and worked on.

**Comment by janmichek** [comment]
Thank you, there are still some open questions in the initial comment. DO we have answers on them?

**Comment by michele-franchi** [comment]
@janmichek endpoint data needs to be checked to figure out if everything is available / can answer these questions.

**Comment by danilosierrac** [comment]
Hi team. Do the names that appear on the left column need to appear untruncated? or can they be truncated?.

**Comment by danilosierrac** [comment]
And also, the "technical information"h - is this internal or shall it appear say through a tooltip hint?

**Comment by janmichek** [comment]
> Hi team. Do the names that appear on the left column need to appear untruncated? or can they be truncated?.

I think it should be truncated, it's decided by its length


> And also, the "technical information"h - is this internal or shall it appear say through a tooltip hint?

Without a tooltip for now 

@danilosierrac

**Comment by janmichek** [comment]
After initial kickof and adjusting some actions,
Found that the actions are impossible to determine of FE, so I suggest adding these to response with MDW

**Name commitment initialized** - This is not possible to show as the Preclaim event is not listed in the activities
**Auction initialized** - There is no way to determine first bid, because the response is paginated
**Auction ended** - There is no way to determine last bid, because the response is paginated
**Activated** - There is no way to determine last bid, because the response is paginated
**Expired** - There is no way to determine last Claim/Transfer/Update as the response is paginated

Some names have an action not defined in initial description

*InternalContractCallEvent*
https://pr-524-aescan.stg.aepps.com/names/a.chain


 and *SpendTxEvent*
https://pr-524-aescan.stg.aepps.com/names/yani.chain

How should we display them?

**Comment by janmichek** [comment]
@michele-franchi WHat you think it should be Data content of these?
![image](https://github.com/aeternity/aescan/assets/15363559/275c4d22-3f82-45fe-bf3c-2805e1f33e17)

![image](https://github.com/aeternity/aescan/assets/15363559/e4906114-d46c-4c72-9608-037f65b8a5a9)

**Comment by michele-franchi** [comment]
@janmichek for "Internal Contract Call" activities we can simply add the entrypoint in the Data column.

**Comment by janmichek** [comment]
> @janmichek for "Internal Contract Call" activities we can simply add the entrypoint in the Data column.

fixed
