### ISSUE TITLE
Network unavailability handling

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#95]
Let user know something went wrong and provide helpful action

Now it just looks 'broken'
- unstable internet connection
- node is down
- coingecko is down
- mdw is down

anything else?

Suggested by @janmichek.

Example of a problem we want to solve here: https://github.com/aeternity/aescan/issues/127

**Comment by janmichek** [comment]
The `data failed to fetch` component which was implemented just for Oracle Events had to be removed, because was colliding with loaders.
There needs to be more adjustments to distinguish to work with loaders. Ideally for the whole app, not just one entity.
https://github.com/aeternity/aescan/pull/419/commits/4487bf6df0e3819f03b8f11f82097b4a97ba3acd

**Comment by janmichek** [comment]
The page should not stop working if the count is not working.
As happened in here

 https://github.com/aeternity/aescan/pull/815
